float32 u           # original image coordinates
float32 v           # original image coordinates
float32 x           # vehicle coordinates according to AUTOSAR coordinate system
float32 y           # vehicle coordinates according to AUTOSAR coordinate system
float32 z           # vehicle coordinates according to AUTOSAR coordinate system
float32 confidence  # scaled 0..1
bool    valid       # Is this point valid according to lane-semseg
