// Generated by gencpp from file g29_force_feedback/ForceFeedback.msg
// DO NOT EDIT!


#ifndef G29_FORCE_FEEDBACK_MESSAGE_FORCEFEEDBACK_H
#define G29_FORCE_FEEDBACK_MESSAGE_FORCEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace g29_force_feedback
{
template <class ContainerAllocator>
struct ForceFeedback_
{
  typedef ForceFeedback_<ContainerAllocator> Type;

  ForceFeedback_()
    : header()
    , position(0.0)
    , torque(0.0)  {
    }
  ForceFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(0.0)
    , torque(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _position_type;
  _position_type position;

   typedef float _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ForceFeedback_

typedef ::g29_force_feedback::ForceFeedback_<std::allocator<void> > ForceFeedback;

typedef boost::shared_ptr< ::g29_force_feedback::ForceFeedback > ForceFeedbackPtr;
typedef boost::shared_ptr< ::g29_force_feedback::ForceFeedback const> ForceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::g29_force_feedback::ForceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::g29_force_feedback::ForceFeedback_<ContainerAllocator1> & lhs, const ::g29_force_feedback::ForceFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::g29_force_feedback::ForceFeedback_<ContainerAllocator1> & lhs, const ::g29_force_feedback::ForceFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace g29_force_feedback

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e090eb9eec6a6e3a1658541a33681145";
  }

  static const char* value(const ::g29_force_feedback::ForceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe090eb9eec6a6e3aULL;
  static const uint64_t static_value2 = 0x1658541a33681145ULL;
};

template<class ContainerAllocator>
struct DataType< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "g29_force_feedback/ForceFeedback";
  }

  static const char* value(const ::g29_force_feedback::ForceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 position\n"
"float32 torque\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::g29_force_feedback::ForceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::g29_force_feedback::ForceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::g29_force_feedback::ForceFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "torque: ";
    Printer<float>::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // G29_FORCE_FEEDBACK_MESSAGE_FORCEFEEDBACK_H
