#include "builtin_interfaces/msg/Time.idl"
#include "autoware_auto_debug_msgs/msg/MultiArrayLayout.idl"

module autoware_auto_debug_msgs {
  module msg {
    struct Float64MultiArrayStamped {
      builtin_interfaces::msg::Time stamp;

      autoware_auto_debug_msgs::msg::MultiArrayLayout layout;

      sequence<double> data;
    };
  };
};
